sensor_status = {
    "kitchen_overhead_light": False,
    "kitchen_window_1": False,
    "kitchen_window_2": False,
    "kitchen_water": False,
    "kitchen_stove": False,
    "kitchen_microwave": False,
    "kitchen_refrigerator": False,
    "kitchen_dishwasher": False,
    "kitchen_door_out": False,
    "livingroom_overhead_light": False,
    "livingroom_window_1": False,
    "livingroom_window_2": False,
    "livingroom_window_3": False,
    "livingroom_lamp_1": False,
    "livingroom_lamp_2": False,
    "livingroom_television": False,
    "livingroom_door_garage": False,
    "livingroom_door_out": False,
    "master_bedroom_overhead_light": False,
    "master_bedroom_window_1": False,
    "master_bedroom_window_2": False,
    "master_bedroom_lamp_1": False,
    "master_bedroom_lamp_2": False,
    "master_bedroom_television": False,
    "bedroom_two_overhead_light": False,
    "bedroom_two_window_1": False,
    "bedroom_two_window_2": False,
    "bedroom_two_lamp_1": False,
    "bedroom_two_lamp_2": False,
    "bedroom_three_overhead_light": False,
    "bedroom_three_window_1": False,
    "bedroom_three_window_2": False,
    "bedroom_three_lamp_1": False,
    "bedroom_three_lamp_2": False,
    "master_bath_overhead_light": False,
    "master_bath_window_1": False,
    "master_bath_exhaust_fan": False,
    "master_bath_water": False,
    "bath_two_overhead_light": False,
    "bath_two_window_1": False,
    "bath_two_exhaust_fan": False,
    "bath_two_water": False,
    "laundry_overhead_light": False,
    "laundry_clothes_washer": False,
    "laundry_clothes_dryer": False,
    "garage_door_1": False,
    "garage_door_2": False,
    "garage_water": False,
}

daily_devices = [
    "Master_Bed_overhead_light",
    "Master_Bed_lamp_1",
    "Master_Bed_lamp_2",
    "Master_Bed_television",
    "Bed_2_overhead_light",
    "Bed_2_lamp_1",
    "Bed_2_lamp_2",
    "Bed_3_overhead_light",
    "Bed_3_lamp_1",
    "Bed_3_lamp_2",
    "Master_Bath_overhead_light",
    "Master_Bath_exhaust_fan",
    "Bath_2_overhead_light",
    "Bath_2_exhaust_fan",
    "Living_Room_overhead_light",
    "Living_Room_lamp_1",
    "Living_Room_lamp_2",
    "Living_Room_television",
    "Kitchen_overhead_light",
    "Kitchen_refrigerator",
    "Laundry_overhead_light",
    "Master_Bed_television",
    "Living_Room_television",
    "Kitchen_stove",
    "Kitchen_oven",
    "Kitchen_microwave",
]

weekly_devices = [
    "Kitchen_dishwasher",
    "Laundry_clothes_dryer",
    "Laundry_clothes_washer",
]

electric = {
    "Master_Bed_overhead_light": 60,
    "Master_Bed_lamp_1": 60,
    "Master_Bed_lamp_2": 60,
    "Bed_2_overhead_light": 60,
    "Bed_2_lamp_1": 60,
    "Bed_2_lamp_2": 60,
    "Bed_3_overhead_light": 60,
    "Bed_3_lamp_1": 60,
    "Bed_3_lamp_2": 60,
    "Master_Bath_overhead_light": 60,
    "Bath_2_overhead_light": 60,
    "Living_Room_overhead_light": 60,
    "Living_Room_lamp_1": 60,
    "Living_Room_lamp_2": 60,
    "Kitchen_overhead_light": 60,
    "Laundry_overhead_light": 60,
    "Master_Bed_television": 100,
    "Living_Room_television": 636,
    "Master_Bath_exhaust_fan": 30,
    "Bath_2_exhaust_fan": 30,
    "Kitchen_stove": 3500,
    "Kitchen_oven": 4000,
    "Kitchen_microwave": 1100,
    "Kitchen_refrigerator": 150,
    "Laundry_clothes_dryer": 3000,
    "Kitchen_dishwasher": 1800,
    "Laundry_clothes_washer": 500,
    "HVAC": 3500,
    "Hot_water_heater": 4500,
}

# watts, duration
electric_daily_duration = {
    "Master_Bed_overhead_light": (60, 150 + 301),
    "Master_Bed_lamp_1": (60, 150 + 301),
    "Master_Bed_lamp_2": (60, 150 + 301),
    "Bed_2_overhead_light": (60, 90 + 271),
    "Bed_2_lamp_1": (60, 90 + 271),
    "Bed_2_lamp_2": (60, 90 + 271),
    "Bed_3_overhead_light": (60, 90 + 271),
    "Bed_3_lamp_1": (60, 90 + 271),
    "Bed_3_lamp_2": (60, 90 + 271),
    "Master_Bath_overhead_light": (60, 150 + 301),
    "Bath_2_overhead_light": (60, 150 + 301),
    "Living_Room_overhead_light": (180, 150 + 301),
    "Living_Room_lamp_1": (60, 150 + 301),
    "Living_Room_lamp_2": (60, 150 + 301),
    "Kitchen_overhead_light": (120, 150 + 301),
    "Laundry_overhead_light": (0, 61),
    "Master_Bed_television": (120, 121),
    "Living_Room_television": (240, 241),
    "Master_Bath_exhaust_fan": (0, 61),
    "Bath_2_exhaust_fan": (0, 61),
    "Kitchen_stove": (15, 16),
    "Kitchen_oven": (45, 46),
    "Kitchen_microwave": (20, 21),
    "Kitchen_refrigerator": (24 * 60, 24 * 60 + 1),
    "Kitchen_dishwasher": (45, 46),
    "Laundry_clothes_dryer": (30, 31),
    "Laundry_clothes_washer": (30, 31),
}

electric_weekend_duration = {
    "Master_Bed_television": 240,
    "Living_Room_television": 480,
    "Kitchen_stove": 30,
    "Kitchen_oven": 60,
    "Kitchen_microwave": 30,
}

water = {
    "Kitchen_dishwasher": (6, 1),
    "Laundry_clothes_washer": (20, 0.85),
    "Master_Bath_water_shower": (25, 0.65),
    "Master_Bath_water_bath": (30, 0.65),
    "Bath_2_water_shower": (25, 0.65),
    "Bath_2_water_bath": (30, 0.65),
}
